### ISSUE TITLE
'btrfs filesystem usage' crashes during device removal

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#303]
Downstream bug [btrfs_stack_stripe_devid(): btrfs killed by SIGSEGV](https://bugzilla.redhat.com/show_bug.cgi?id=1887645)

btrfs-progs-5.7-5.fc33_x86_64
kernel- 5.9.0-0.rc8.28.fc34.x86_64
Two device btrfs. Removal of one device is in progress. 'btrfs fi us' crashes.

```
[New LWP 5515]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `btrfs fi us /mnt/fire'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000559b9fee64a3 in btrfs_stack_stripe_devid (s=0x7ffd96f73008) at ./ctree.h:1598
1598	./ctree.h: No such file or directory.

Thread 1 (Thread 0x7fcc005db8c0 (LWP 5515)):
#0  0x0000559b9fee64a3 in btrfs_stack_stripe_devid (s=0x7ffd96f73008) at ./ctree.h:1598
No locals.
#1  add_info_to_list (chunk=<optimized out>, info_count=0x7ffd96f7067c, info_ptr=<optimized out>) at cmds/filesystem-usage.c:59
        i = <optimized out>
        p = 0x0
        stripe = 0x7ffd96f73008
        devid = <optimized out>
        type = 17592186048512
        size = 2
        num_stripes = 1850
        j = <optimized out>
        type = <optimized out>
        size = <optimized out>
        num_stripes = <optimized out>
        j = <optimized out>
        i = <optimized out>
        p = <optimized out>
        stripe = <optimized out>
        devid = <optimized out>
        tmp = <optimized out>
        res = <optimized out>
#2  load_chunk_info (fd=fd@entry=3, info_ptr=info_ptr@entry=0x7ffd96f70688, info_count=info_count@entry=0x7ffd96f7067c) at cmds/filesystem-usage.c:185
        item = <optimized out>
        ret = <optimized out>
        args = {key = {tree_id = 3, min_objectid = 0, max_objectid = 18446744073709551615, min_offset = 0, max_offset = 18446744073709551615, min_transid = 0, max_transid = 18446744073709551615, min_type = 255, max_type = 0, nr_items = 34, unused = 0, unused1 = 0, unused2 = 0, unused3 = 0, unused4 = 0}, buf = "h\a\000\000\000\000\000\000\001\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\330\000\000\000b\000\000\000\002\000\000\000\000\000\000\000\000\260oZ$\000\000\000\000\000\000\000#\000\000\000\000\020\000\000\000\020\000\000\000\020\000\000\000\000\000\000\000\000\000\000:\a", '\000' <repeats 20 times>, "\016A3R\244\063K\202\254\001u\211\204H(;s\354\275$D\270H\b\230\306!8{(k\th\a\000\000\000\000\000\000\001\000\000\000\000\000\000\000\003\000\000\000\000\000\000\000\330\000\000\000b\000\000\000\003\000\000\000\000\000\000\000\000\000\000@$\000\000\000\000\000\000\204\001\000\000\000\000\020\000\000\000\020\000\000\000\020", '\000' <repeats 32 times>...}
        sk = 0x7ffd96f6f590
        sh = 0x7ffd96f6f5f8
        off = 32
        i = 0
        e = <optimized out>
#3  0x0000559b9feee461 in load_chunk_and_device_info (devcount=0x7ffd96f70678, devinfo=0x7ffd96f70680, chunkcount=0x7ffd96f7067c, chunkinfo=0x7ffd96f70688, fd=3) at cmds/filesystem-usage.c:1126
        ret = <optimized out>
        ret = <optimized out>
#4  cmd_filesystem_usage (cmd=<optimized out>, argc=<optimized out>, argv=0x7ffd96f70858) at cmds/filesystem-usage.c:1126
        fd = 3
        dirstream = 0x559ba0b982a0
        chunkinfo = 0x559ba0ba02e0
        devinfo = 0x0
        chunkcount = 101
        devcount = 0
        ret = 0
        unit_mode = 512
        i = 1
        more_than_one = 0
        tabular = 0
#5  0x0000559b9feb0dd0 in cmd_execute (argv=0x7ffd96f70850, argc=3, cmd=0x559b9ff8c580 <cmd_struct_filesystem>) at cmds/commands.h:125
No locals.
#6  main (argc=3, argv=0x7ffd96f70850) at btrfs.c:402
        cmd = 0x559b9ff8c580 <cmd_struct_filesystem>
        bname = <optimized out>
        ret = <optimized out>
From                To                  Syms Read   Shared Object Library
0x00007fcc008f7310  0x00007fcc008fa967  Yes         /lib64/libuuid.so.1
0x00007fcc008c8a10  0x00007fcc008e51b2  Yes         /lib64/libblkid.so.1
0x00007fcc008aa5f0  0x00007fcc008b7b5b  Yes         /lib64/libz.so.1
0x00007fcc00887190  0x00007fcc008a1e68  Yes         /lib64/liblzo2.so.2
0x00007fcc007d4060  0x00007fcc00874ce8  Yes         /lib64/libzstd.so.1
0x00007fcc007b3a90  0x00007fcc007c2125  Yes         /lib64/libpthread.so.0
0x00007fcc00604690  0x00007fcc0075188d  Yes         /lib64/libc.so.6
0x00007fcc00916090  0x00007fcc00936f96  Yes         /lib64/ld-linux-x86-64.so.2
$1 = 0x0
No symbol "__glib_assert_msg" in current context.
rax            0x2                 2
rbx            0x100000001000      17592186048512
rcx            0x7ffd96f70688      140727136224904
rdx            0x559ba0ba0f60      94126904840032
rsi            0x65                101
rdi            0x7fcc007a3a00      140514158066176
rbp            0x6962732f7273752f  0x6962732f7273752f
rsp            0x7ffd96f6f550      0x7ffd96f6f550
r8             0x65                101
r9             0x7fcc007a3a60      140514158066272
r10            0x7ffd96f7dd88      140727136279944
r11            0x60                96
r12            0x7ffd96f7dd88      140727136279944
r13            0x73a               1850
r14            0x7ffd96f7067c      140727136224892
r15            0x7ffd96f73008      140727136235528
rip            0x559b9fee64a3      0x559b9fee64a3 <load_chunk_info+323>
eflags         0x10283             [ CF SF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
st0            0                   (raw 0x00000000000000000000)
st1            0                   (raw 0x00000000000000000000)
st2            0                   (raw 0x00000000000000000000)
st3            0                   (raw 0x00000000000000000000)
st4            0                   (raw 0x00000000000000000000)
st5            0                   (raw 0x00000000000000000000)
st6            0                   (raw 0x00000000000000000000)
st7            0                   (raw 0x00000000000000000000)
fctrl          0x37f               895
fstat          0x0                 0
ftag           0xffff              65535
fiseg          0x0                 0
fioff          0x0                 0
foseg          0x0                 0
fooff          0x0                 0
fop            0x0                 0
mxcsr          0x1f80              [ IM DM ZM OM UM PM ]
ymm0           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm1           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm2           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm3           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm4           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x8000000000000000, 0x0, 0x0}, v32_int8 = {0x0 <repeats 15 times>, 0xff, 0x0 <repeats 16 times>}, v16_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x0, 0x0, 0x0, 0xff000000, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0xff00000000000000, 0x0, 0x0}, v2_int128 = {0xff000000000000000000000000000000, 0x0}}
ymm5           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x6, 0x0, 0x0, 0x0, 0x2a, 0x0, 0x0, 0x0, 0x7, 0x0 <repeats 23 times>}, v16_int16 = {0x6, 0x0, 0x2a, 0x0, 0x7, 0x0 <repeats 11 times>}, v8_int32 = {0x6, 0x2a, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x2a00000006, 0x7, 0x0, 0x0}, v2_int128 = {0x70000002a00000006, 0x0}}
ymm6           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0xe0, 0x10, 0xeb, 0x9f, 0x9b, 0x55, 0x0 <repeats 26 times>}, v16_int16 = {0x10e0, 0x9feb, 0x559b, 0x0 <repeats 13 times>}, v8_int32 = {0x9feb10e0, 0x559b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x559b9feb10e0, 0x0, 0x0, 0x0}, v2_int128 = {0x559b9feb10e0, 0x0}}
ymm7           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm8           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm9           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm10          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm11          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm12          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm13          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm14          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
ymm15          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x0, 0x0}}
Dump of assembler code for function load_chunk_info:
   0x0000559b9fee6360 <+0>:	push   %r15
   0x0000559b9fee6362 <+2>:	push   %r14
   0x0000559b9fee6364 <+4>:	push   %r13
   0x0000559b9fee6366 <+6>:	push   %r12
   0x0000559b9fee6368 <+8>:	push   %rbp
   0x0000559b9fee6369 <+9>:	push   %rbx
   0x0000559b9fee636a <+10>:	sub    $0x1000,%rsp
   0x0000559b9fee6371 <+17>:	orq    $0x0,(%rsp)
   0x0000559b9fee6376 <+22>:	sub    $0x58,%rsp
   0x0000559b9fee637a <+26>:	mov    $0x200,%ecx
   0x0000559b9fee637f <+31>:	mov    %edi,0x34(%rsp)
   0x0000559b9fee6383 <+35>:	lea    0x40(%rsp),%rdi
   0x0000559b9fee6388 <+40>:	mov    %rsi,%r14
   0x0000559b9fee638b <+43>:	mov    %rdx,%r13
   0x0000559b9fee638e <+46>:	mov    %r14,%r15
   0x0000559b9fee6391 <+49>:	mov    %r13,%r12
   0x0000559b9fee6394 <+52>:	mov    %fs:0x28,%rax
   0x0000559b9fee639d <+61>:	mov    %rax,0x1048(%rsp)
   0x0000559b9fee63a5 <+69>:	xor    %eax,%eax
   0x0000559b9fee63a7 <+71>:	mov    %rdi,0x38(%rsp)
   0x0000559b9fee63ac <+76>:	rep stos %rax,%es:(%rdi)
   0x0000559b9fee63af <+79>:	movl   $0xff,0x78(%rsp)
   0x0000559b9fee63b7 <+87>:	movq   $0x3,0x40(%rsp)
   0x0000559b9fee63c0 <+96>:	movq   $0xffffffffffffffff,0x50(%rsp)
   0x0000559b9fee63c9 <+105>:	movq   $0xffffffffffffffff,0x60(%rsp)
   0x0000559b9fee63d2 <+114>:	movq   $0xffffffffffffffff,0x70(%rsp)
   0x0000559b9fee63db <+123>:	movl   $0x1000,0x80(%rsp)
   0x0000559b9fee63e6 <+134>:	callq  0x559b9feb0100 <__errno_location@plt>
   0x0000559b9fee63eb <+139>:	mov    %rax,0x28(%rsp)
   0x0000559b9fee63f0 <+144>:	mov    0x38(%rsp),%rdx
   0x0000559b9fee63f5 <+149>:	mov    0x34(%rsp),%edi
   0x0000559b9fee63f9 <+153>:	xor    %eax,%eax
   0x0000559b9fee63fb <+155>:	mov    $0xd0009411,%esi
   0x0000559b9fee6400 <+160>:	callq  0x559b9feb04e0 <ioctl@plt>
   0x0000559b9fee6405 <+165>:	mov    0x28(%rsp),%rcx
   0x0000559b9fee640a <+170>:	cmpl   $0x1,(%rcx)
   0x0000559b9fee640d <+173>:	je     0x559b9fee6620 <load_chunk_info+704>
   0x0000559b9fee6413 <+179>:	test   %eax,%eax
   0x0000559b9fee6415 <+181>:	js     0x559b9fee6600 <load_chunk_info+672>
   0x0000559b9fee641b <+187>:	mov    0x80(%rsp),%eax
   0x0000559b9fee6422 <+194>:	test   %eax,%eax
   0x0000559b9fee6424 <+196>:	je     0x559b9fee656d <load_chunk_info+525>
   0x0000559b9fee642a <+202>:	lea    0xa8(%rsp),%rax
   0x0000559b9fee6432 <+210>:	xor    %ebp,%ebp
   0x0000559b9fee6434 <+212>:	mov    %r15,%r13
   0x0000559b9fee6437 <+215>:	mov    %r12,%r14
   0x0000559b9fee643a <+218>:	movl   $0x0,0x30(%rsp)
   0x0000559b9fee6442 <+226>:	mov    %rax,0x20(%rsp)
   0x0000559b9fee6447 <+231>:	mov    0x20(%rsp),%rax
   0x0000559b9fee644c <+236>:	lea    (%rax,%rbp,1),%rcx
   0x0000559b9fee6450 <+240>:	mov    %rcx,0x10(%rsp)
   0x0000559b9fee6455 <+245>:	lea    0x20(%rbp),%rcx
   0x0000559b9fee6459 <+249>:	add    %rcx,%rax
   0x0000559b9fee645c <+252>:	mov    %rcx,0x18(%rsp)
   0x0000559b9fee6461 <+257>:	mov    (%rax),%rcx
   0x0000559b9fee6464 <+260>:	mov    0x18(%rax),%rbx
   0x0000559b9fee6468 <+264>:	mov    %rcx,0x8(%rsp)
   0x0000559b9fee646d <+269>:	movzwl 0x2c(%rax),%ecx
   0x0000559b9fee6471 <+273>:	test   %cx,%cx
   0x0000559b9fee6474 <+276>:	je     0x559b9fee6502 <load_chunk_info+418>
   0x0000559b9fee647a <+282>:	movzwl %cx,%edx
   0x0000559b9fee647d <+285>:	movzwl %cx,%ebp
   0x0000559b9fee6480 <+288>:	lea    0x30(%rax),%r15
   0x0000559b9fee6484 <+292>:	mov    %r13,%rcx
   0x0000559b9fee6487 <+295>:	sub    $0x1,%edx
   0x0000559b9fee648a <+298>:	mov    %rbp,%r13
   0x0000559b9fee648d <+301>:	shl    $0x5,%rdx
   0x0000559b9fee6491 <+305>:	lea    0x50(%rax,%rdx,1),%r10
   0x0000559b9fee6496 <+310>:	mov    %r10,%r12
   0x0000559b9fee6499 <+313>:	nopl   0x0(%rax)
   0x0000559b9fee64a0 <+320>:	mov    (%r14),%r8d
=> 0x0000559b9fee64a3 <+323>:	mov    (%r15),%rbp
   0x0000559b9fee64a6 <+326>:	mov    (%rcx),%rdi
   0x0000559b9fee64a9 <+329>:	test   %r8d,%r8d
   0x0000559b9fee64ac <+332>:	jle    0x559b9fee65b0 <load_chunk_info+592>
   0x0000559b9fee64b2 <+338>:	lea    -0x1(%r8),%edx
   0x0000559b9fee64b6 <+342>:	mov    %rdi,%rax
   0x0000559b9fee64b9 <+345>:	shl    $0x5,%rdx
   0x0000559b9fee64bd <+349>:	lea    0x20(%rdi,%rdx,1),%rsi
   0x0000559b9fee64c2 <+354>:	jmp    0x559b9fee64d5 <load_chunk_info+373>
   0x0000559b9fee64c4 <+356>:	nopl   0x0(%rax)
   0x0000559b9fee64c8 <+360>:	add    $0x20,%rax
   0x0000559b9fee64cc <+364>:	cmp    %rax,%rsi
   0x0000559b9fee64cf <+367>:	je     0x559b9fee65b0 <load_chunk_info+592>
   0x0000559b9fee64d5 <+373>:	mov    %rax,%rdx
   0x0000559b9fee64d8 <+376>:	cmp    (%rax),%rbx
   0x0000559b9fee64db <+379>:	jne    0x559b9fee64c8 <load_chunk_info+360>
   0x0000559b9fee64dd <+381>:	cmp    0x10(%rax),%rbp
   0x0000559b9fee64e1 <+385>:	jne    0x559b9fee64c8 <load_chunk_info+360>
   0x0000559b9fee64e3 <+387>:	cmp    %r13,0x18(%rax)
   0x0000559b9fee64e7 <+391>:	jne    0x559b9fee64c8 <load_chunk_info+360>
   0x0000559b9fee64e9 <+393>:	mov    0x8(%rsp),%rax
   0x0000559b9fee64ee <+398>:	add    0x8(%rdx),%rax
   0x0000559b9fee64f2 <+402>:	add    $0x20,%r15
   0x0000559b9fee64f6 <+406>:	mov    %rax,0x8(%rdx)
   0x0000559b9fee64fa <+410>:	cmp    %r12,%r15
   0x0000559b9fee64fd <+413>:	jne    0x559b9fee64a0 <load_chunk_info+320>
   0x0000559b9fee64ff <+415>:	mov    %rcx,%r13
   0x0000559b9fee6502 <+418>:	mov    0x10(%rsp),%rax
   0x0000559b9fee6507 <+423>:	addl   $0x1,0x30(%rsp)
   0x0000559b9fee650c <+428>:	mov    0x30(%rsp),%edi
   0x0000559b9fee6510 <+432>:	mov    0x18(%rax),%ecx
   0x0000559b9fee6513 <+435>:	mov    0x1c(%rax),%ebp
   0x0000559b9fee6516 <+438>:	mov    0x8(%rax),%rdx
   0x0000559b9fee651a <+442>:	add    0x18(%rsp),%rbp
   0x0000559b9fee651f <+447>:	mov    %ecx,0x78(%rsp)
   0x0000559b9fee6523 <+451>:	mov    0x10(%rax),%rax
   0x0000559b9fee6527 <+455>:	mov    %rdx,0x48(%rsp)
   0x0000559b9fee652c <+460>:	add    $0x1,%rax
   0x0000559b9fee6530 <+464>:	mov    %rax,0x58(%rsp)
   0x0000559b9fee6535 <+469>:	cmp    %edi,0x80(%rsp)
   0x0000559b9fee653c <+476>:	ja     0x559b9fee6447 <load_chunk_info+231>
   0x0000559b9fee6542 <+482>:	mov    %r13,%r15
   0x0000559b9fee6545 <+485>:	mov    %r14,%r12
   0x0000559b9fee6548 <+488>:	test   %rax,%rax
   0x0000559b9fee654b <+491>:	jne    0x559b9fee63f0 <load_chunk_info+144>
   0x0000559b9fee6551 <+497>:	add    $0x1,%ecx
   0x0000559b9fee6554 <+500>:	mov    %ecx,0x78(%rsp)
   0x0000559b9fee6558 <+504>:	jne    0x559b9fee63f0 <load_chunk_info+144>
   0x0000559b9fee655e <+510>:	add    $0x1,%rdx
   0x0000559b9fee6562 <+514>:	mov    %rdx,0x48(%rsp)
   0x0000559b9fee6567 <+519>:	jne    0x559b9fee63f0 <load_chunk_info+144>
   0x0000559b9fee656d <+525>:	movslq (%r12),%rsi
   0x0000559b9fee6571 <+529>:	mov    (%r15),%rdi
   0x0000559b9fee6574 <+532>:	mov    $0x20,%edx
   0x0000559b9fee6579 <+537>:	lea    -0x3060(%rip),%rcx        # 0x559b9fee3520 <cmp_chunk_info>
   0x0000559b9fee6580 <+544>:	callq  0x559b9feb0210 <qsort@plt>
   0x0000559b9fee6585 <+549>:	xor    %eax,%eax
   0x0000559b9fee6587 <+551>:	mov    0x1048(%rsp),%rcx
   0x0000559b9fee658f <+559>:	sub    %fs:0x28,%rcx
   0x0000559b9fee6598 <+568>:	jne    0x559b9fee6618 <load_chunk_info+696>
   0x0000559b9fee659a <+570>:	add    $0x1058,%rsp
   0x0000559b9fee65a1 <+577>:	pop    %rbx
   0x0000559b9fee65a2 <+578>:	pop    %rbp
   0x0000559b9fee65a3 <+579>:	pop    %r12
   0x0000559b9fee65a5 <+581>:	pop    %r13
   0x0000559b9fee65a7 <+583>:	pop    %r14
   0x0000559b9fee65a9 <+585>:	pop    %r15
   0x0000559b9fee65ab <+587>:	retq   
   0x0000559b9fee65ac <+588>:	nopl   0x0(%rax)
   0x0000559b9fee65b0 <+592>:	lea    0x5(%r8,%r8,4),%esi
   0x0000559b9fee65b5 <+597>:	mov    %rcx,(%rsp)
   0x0000559b9fee65b9 <+601>:	shl    $0x4,%esi
   0x0000559b9fee65bc <+604>:	movslq %esi,%rsi
   0x0000559b9fee65bf <+607>:	callq  0x559b9feb08f0 <realloc@plt>
   0x0000559b9fee65c4 <+612>:	mov    (%rsp),%rcx
   0x0000559b9fee65c8 <+616>:	test   %rax,%rax
   0x0000559b9fee65cb <+619>:	je     0x559b9fee662a <load_chunk_info+714>
   0x0000559b9fee65cd <+621>:	mov    %rax,(%rcx)
   0x0000559b9fee65d0 <+624>:	movslq (%r14),%rdx
   0x0000559b9fee65d3 <+627>:	mov    %rdx,%rsi
   0x0000559b9fee65d6 <+630>:	shl    $0x5,%rdx
   0x0000559b9fee65da <+634>:	add    %rax,%rdx
   0x0000559b9fee65dd <+637>:	add    $0x1,%esi
   0x0000559b9fee65e0 <+640>:	mov    0x8(%rsp),%rax
   0x0000559b9fee65e5 <+645>:	mov    %esi,(%r14)
   0x0000559b9fee65e8 <+648>:	mov    %rbp,0x10(%rdx)
   0x0000559b9fee65ec <+652>:	mov    %rbx,(%rdx)
   0x0000559b9fee65ef <+655>:	movq   $0x0,0x8(%rdx)
   0x0000559b9fee65f7 <+663>:	mov    %r13,0x18(%rdx)
   0x0000559b9fee65fb <+667>:	jmpq   0x559b9fee64f2 <load_chunk_info+402>
   0x0000559b9fee6600 <+672>:	xor    %eax,%eax
   0x0000559b9fee6602 <+674>:	lea    0x6eb07(%rip),%rdi        # 0x559b9ff55110
   0x0000559b9fee6609 <+681>:	callq  0x559b9ff08ab0 <__btrfs_error>
   0x0000559b9fee660e <+686>:	mov    $0x1,%eax
   0x0000559b9fee6613 <+691>:	jmpq   0x559b9fee6587 <load_chunk_info+551>
   0x0000559b9fee6618 <+696>:	callq  0x559b9feb0360 <__stack_chk_fail@plt>
   0x0000559b9fee661d <+701>:	nopl   (%rax)
   0x0000559b9fee6620 <+704>:	mov    $0xffffffff,%eax
   0x0000559b9fee6625 <+709>:	jmpq   0x559b9fee6587 <load_chunk_info+551>
   0x0000559b9fee662a <+714>:	mov    (%rcx),%rdi
   0x0000559b9fee662d <+717>:	mov    %rcx,%r14
   0x0000559b9fee6630 <+720>:	callq  0x559b9feb0050 <free@plt>
   0x0000559b9fee6635 <+725>:	xor    %eax,%eax
   0x0000559b9fee6637 <+727>:	lea    0x5cde1(%rip),%rdi        # 0x559b9ff4341f
   0x0000559b9fee663e <+734>:	callq  0x559b9ff08ab0 <__btrfs_error>
   0x0000559b9fee6643 <+739>:	movq   $0x0,(%r14)
   0x0000559b9fee664a <+746>:	mov    $0x1,%eax
   0x0000559b9fee664f <+751>:	jmpq   0x559b9fee6587 <load_chunk_info+551>
End of assembler dump.
```

**Comment by kdave** [comment]
Same fix as for #300, closing.
