### ISSUE TITLE
[misc-tests] 019-receive-clones-on-munted-subvol: memory leak

### ISSUE THREAD

**Issue by matthiaskrgr** [kdave/btrfs-progs#33]
compiled with ````clang 4.0````
CFLAGS: ````-g3 -O0 -Wall -fno-omit-frame-pointer -fsanitize-address-use-after-scope  -fno-optimize-sibling-calls -fsanitize=address,undefined````
based on master branch / btrfs progs 4.10.1  / 15d37febbce1255c1042764690a5e5375d014616
run command (as root): ````UBSAN_OPTIONS=print_stacktrace=1 make test -k````

[misc-tests-results.txt](https://github.com/kdave/btrfs-progs/files/853006/misc-tests-results.txt)

From the stacktrace it looks like this memleak is only caused by the test-code itself and not by the code being tested.

````
[...]
############### mount -o loop /home/matthias/vcs/github/btrfs-progs/tests/test.img /home/matthias/vcs/github/btrfs-progs/tests/mnt
############### /home/matthias/vcs/github/btrfs-progs/btrfs subvolume create /home/matthias/vcs/github/btrfs-progs/tests/mnt/foo
Create subvolume '/home/matthias/vcs/github/btrfs-progs/tests/mnt/foo'
############### /home/matthias/vcs/github/btrfs-progs/btrfs subvolume create /home/matthias/vcs/github/btrfs-progs/tests/mnt/bar
Create subvolume '/home/matthias/vcs/github/btrfs-progs/tests/mnt/bar'
############### /home/matthias/vcs/github/btrfs-progs/btrfs subvolume create /home/matthias/vcs/github/btrfs-progs/tests/mnt/baz
Create subvolume '/home/matthias/vcs/github/btrfs-progs/tests/mnt/baz'
############### /home/matthias/vcs/github/btrfs-progs/btrfs subvolume create /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap
Create subvolume '/home/matthias/vcs/github/btrfs-progs/tests/mnt/snap'
############### dd of=/home/matthias/vcs/github/btrfs-progs/tests/mnt/foo/file_a bs=4096 count=32
0+0 records in
0+0 records out
0 bytes copied, 0.0512679 s, 0.0 kB/s
############### dd of=/home/matthias/vcs/github/btrfs-progs/tests/mnt/bar/file_b bs=4096 count=32
0+0 records in
0+0 records out
0 bytes copied, 3.5627e-05 s, 0.0 kB/s
############### cp --reflink=always /home/matthias/vcs/github/btrfs-progs/tests/mnt/foo/file_a /home/matthias/vcs/github/btrfs-progs/tests/mnt/baz/file_a
############### cp --reflink=always /home/matthias/vcs/github/btrfs-progs/tests/mnt/bar/file_b /home/matthias/vcs/github/btrfs-progs/tests/mnt/baz/file_b
############### /home/matthias/vcs/github/btrfs-progs/btrfs subvolume snapshot -r /home/matthias/vcs/github/btrfs-progs/tests/mnt/foo /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.0
Create a readonly snapshot of '/home/matthias/vcs/github/btrfs-progs/tests/mnt/foo' in '/home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.0'
############### /home/matthias/vcs/github/btrfs-progs/btrfs send -f ./send-test-dir/foo.0.snap /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.0
At subvol /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.0
############### /home/matthias/vcs/github/btrfs-progs/btrfs subvolume snapshot -r /home/matthias/vcs/github/btrfs-progs/tests/mnt/bar /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/bar.0
Create a readonly snapshot of '/home/matthias/vcs/github/btrfs-progs/tests/mnt/bar' in '/home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/bar.0'
############### /home/matthias/vcs/github/btrfs-progs/btrfs send -f ./send-test-dir/bar.0.snap /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/bar.0
At subvol /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/bar.0
############### cp --reflink=always /home/matthias/vcs/github/btrfs-progs/tests/mnt/foo/file_a /home/matthias/vcs/github/btrfs-progs/tests/mnt/foo/file_a.clone
############### rm -f -- /home/matthias/vcs/github/btrfs-progs/tests/mnt/foo/file_a
############### /home/matthias/vcs/github/btrfs-progs/btrfs subvolume snapshot -r /home/matthias/vcs/github/btrfs-progs/tests/mnt/foo /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.1
Create a readonly snapshot of '/home/matthias/vcs/github/btrfs-progs/tests/mnt/foo' in '/home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.1'
############### /home/matthias/vcs/github/btrfs-progs/btrfs send -p /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.0 -f ./send-test-dir/foo.1.snap /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.1
At subvol /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.1
############### /home/matthias/vcs/github/btrfs-progs/btrfs subvolume snapshot -r /home/matthias/vcs/github/btrfs-progs/tests/mnt/baz /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/baz.0
Create a readonly snapshot of '/home/matthias/vcs/github/btrfs-progs/tests/mnt/baz' in '/home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/baz.0'
############### /home/matthias/vcs/github/btrfs-progs/btrfs send -p /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.1 -c /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/bar.0 -f ./send-test-dir/baz.0.snap /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/baz.0
At subvol /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/baz.0
############### /home/matthias/vcs/github/btrfs-progs/fssum -A -f -w ./send-test-dir/foo.0.fssum /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.0

=================================================================
==6787==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32816 byte(s) in 1 object(s) allocated from:
    #0 0x4c20cc in malloc /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66:3
    #1 0x7f225ae42e93 in __alloc_dir /usr/src/debug/glibc-2.24-33-ge9e69e4/dirent/../sysdeps/posix/opendir.c:247

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x4c247e in realloc /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:79:3
    #1 0x4f3b5b in sum /home/matthias/vcs/github/btrfs-progs/tests/fssum.c:492:15
    #2 0x4f8ebe in main /home/matthias/vcs/github/btrfs-progs/tests/fssum.c:786:2
    #3 0x7f225ad9b400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 65 byte(s) in 1 object(s) allocated from:
    #0 0x4c20cc in malloc /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66:3
    #1 0x4f0ac4 in alloc /home/matthias/vcs/github/btrfs-progs/tests/fssum.c:163:12
    #2 0x4f0fe4 in sum_to_string /home/matthias/vcs/github/btrfs-progs/tests/fssum.c:214:12
    #3 0x4f9032 in main /home/matthias/vcs/github/btrfs-progs/tests/fssum.c:801:27
    #4 0x7f225ad9b400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Indirect leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x4ae7b3 in strdup /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:550:3
    #1 0x4f3c87 in sum /home/matthias/vcs/github/btrfs-progs/tests/fssum.c:499:23
    #2 0x4f8ebe in main /home/matthias/vcs/github/btrfs-progs/tests/fssum.c:786:2
    #3 0x7f225ad9b400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

SUMMARY: AddressSanitizer: 33912 byte(s) leaked in 4 allocation(s).
failed: /home/matthias/vcs/github/btrfs-progs/fssum -A -f -w ./send-test-dir/foo.0.fssum /home/matthias/vcs/github/btrfs-progs/tests/mnt/snap/foo.0
test failed for case 019-receive-clones-on-munted-subvol
````

**Comment by adam900710** [comment]
The leak is caused by fssum.

IIRC it's copied from LTP or xfstest.

Do we need to fix it?

**Comment by matthiaskrgr** [comment]
Hi, I can't reproduce this leak anymore with 0607132 / 4.12, thus closing this ticket.
