### ISSUE TITLE
btrfs check --repair segfaults 

### ISSUE THREAD

**Issue by bentau** [kdave/btrfs-progs#409]
`btrfs check --repair /dev/sdd2` segfaulted

```Device extent[2, 1681514299392, 1073741824] didn't find the relative chunk.
Device extent[2, 1685809266688, 1073741824] didn't find the relative chunk.
Device extent[2, 1706210361344, 1073741824] didn't find the relative chunk.
Device extent[2, 1854386733056, 1073741824] didn't find the relative chunk.
Reset extent item (1544071184384) generation to 58844
Reset extent item (1544071200768) generation to 58844
Reset extent item (1544071233536) generation to 58844
ERROR: invalid generation for extent 1544071364608, have 58844 expect (0, 58642]
ref mismatch on [1544071364608 16384] extent item 0, found 1
tree backref 1544071364608 root 3 not found in extent tree
backpointer mismatch on [1544071364608 16384]

Program received signal SIGSEGV, Segmentation fault.
btrfs_commit_transaction (trans=trans@entry=0xffffffffffffffe2, root=0x55555564b280) at kernel-shared/transaction.c:167
167             u64 transid = trans->transid;
(gdb) rbt
Undefined command: "rbt".  Try "help".
(gdb) bt
#0  btrfs_commit_transaction (trans=trans@entry=0xffffffffffffffe2, root=0x55555564b280) at kernel-shared/transaction.c:167
#1  0x000055555559636d in fixup_extent_refs (rec=0x55556b98a300, extent_cache=0x7fffffffdf60) at check/main.c:7739
#2  check_extent_refs (extent_cache=0x7fffffffdf60, root=0x555556aa4de0) at check/main.c:8208
#3  check_chunks_and_extents () at check/main.c:9013
#4  do_check_chunks_and_extents () at check/main.c:9076
#5  0x000055555559aadd in cmd_check (cmd=0x55555563ae40 <cmd_struct_check>, argc=<optimized out>, argv=<optimized out>)
    at check/main.c:10778
#6  0x000055555556b215 in cmd_execute (argv=0x7fffffffe8a0, argc=3, cmd=0x55555563ae40 <cmd_struct_check>) at cmds/commands.h:125
#7  main (argc=3, argv=0x7fffffffe8a0) at btrfs.c:405
(gdb) list
162     }
163
164     int btrfs_commit_transaction(struct btrfs_trans_handle *trans,
165                                  struct btrfs_root *root)
166     {
167             u64 transid = trans->transid;
168             int ret = 0;
169             struct btrfs_fs_info *fs_info = root->fs_info;
170             struct btrfs_space_info *sinfo;
171
```

**Comment by kdave** [comment]
Thanks for the report. Fixed by https://lore.kernel.org/linux-btrfs//20211104141610.48818-1-realwakka@gmail.com and merged to devel.
