### ISSUE TITLE
[TEST/fuzz] 001-simple-check-unmounted segfaults (i686, btrfs-progs 5.16.1, kernel 5.17-rc3)

### ISSUE THREAD

**Issue by ernsteiswuerfel** [kdave/btrfs-progs#446]
Running fuzz-tests.sh von my Pentium4 box gives me:
```
 # ./fuzz-tests.sh 
    [TEST/fuzz]   001-simple-check-unmounted
/root/build/btrfs-progs/tests/common: line 247: 31224 Segmentation fault      (core dumped) "${cmd_array[@]}" >> "$RESULTS" 2>&1
mayfail: returned code 139 (SEGFAULT), not ignored
test failed for case 001-simple-check-unmounted
```
systemd-autogenerated coredum shows:
```
Core was generated by `/root/build/btrfs-progs/btrfs check /root/build/btrfs-progs/tests/fuzz-tests/im'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  btrfs_search_slot (trans=0x0, root=0x0, key=0xbfa35907, p=0xbfa35998, ins_len=0, cow=0)
    at kernel-shared/ctree.c:1357
1357		struct btrfs_fs_info *fs_info = root->fs_info;
```
and this kernel dmesg:
```
[12495.211412] btrfs[31224]: segfault at 1d0 ip b7df24cb sp bfa356b0 error 4 in btrfs[b7de7000+a7000]
[12495.211552] Code: 00 8b 84 24 18 01 00 00 89 44 24 10 8b bc 24 1c 01 00 00 65 a1 14 00 00 00 89 84 24 ec 00 00 00 31 c0 0f b6 47 40 88 44 24 17 <8b> 85 d0 01 00 00 89 04 24 0f b6 47 41 88 44 24 16 83 bc 24 20 01
```
[fuzz-tests-results.txt](https://github.com/kdave/btrfs-progs/files/8019535/fuzz-tests-results.txt)

**Comment by adam900710** [comment]
Mind to provide the full call trace?

It's the caller who calls `btrfs_search_slot()` with NULL root is the culprit afaik.

**Comment by ernsteiswuerfel** [comment]
```
Core was generated by `/root/build/btrfs-progs/btrfs check /root/build/btrfs-progs/tests/fuzz-tests/im'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  btrfs_search_slot (trans=0x0, root=0x0, key=0xbff39127, p=0xbff391b8, ins_len=0, cow=0) at kernel-shared/ctree.c:1357
1357		struct btrfs_fs_info *fs_info = root->fs_info;
(gdb) bt
#0  btrfs_search_slot (trans=0x0, root=0x0, key=0xbff39127, p=0xbff391b8, ins_len=0, cow=0) at kernel-shared/ctree.c:1357
#1  0xb7ecfbea in build_roots_info_cache () at check/main.c:9619
#2  repair_root_items () at check/main.c:9832
#3  cmd_check (cmd=0xb7f68350 <cmd_struct_check>, argc=2, argv=0xbff39588) at check/main.c:10629
#4  0xb7e50326 in cmd_execute (argv=0xbff39588, argc=<optimized out>, cmd=0xb7f68350 <cmd_struct_check>) at cmds/commands.h:125
#5  main (argc=<optimized out>, argv=0xbff39588) at btrfs.c:405
```

**Comment by adam900710** [comment]
It seems to be caused by the recent extent tree v2 code change.

@josefbacik It looks like `btrfs_extent_root()` can not handle global extent root when bytenr is 0?
