### ISSUE TITLE
btrfs inspect-internal tree-stats crash

### ISSUE THREAD

**Issue by LaurentBonnaud** [kdave/btrfs-progs#520]
Hi,

with those software versions:
```
# btrfs --version
btrfs-progs v5.16.2
```
```
# uname -a
Linux xeelee 5.19.11-051911-generic #202209231341 SMP PREEMPT_DYNAMIC Fri Sep 23 14:11:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I see the following segfault:

```
# btrfs inspect-internal tree-stats /dev/nvme0n1p2
WARNING: /dev/nvme0n1p2 already mounted, results may be inaccurate
Calculating size of root tree
        Total size: 144.00KiB
                Inline data: 0.00B
        Total seeks: 6
                Forward seeks: 5
                Backward seeks: 1
                Avg seek len: 228.75MiB
        Total clusters: 1
                Avg cluster size: 48.00KiB
                Min cluster size: 48.00KiB
                Max cluster size: 48.00KiB
        Total disk spread: 725.61MiB
        Total read time: 0 s 12 us
        Levels: 2
        Total nodes: 9
                On level 0:        8
                On level 1:        1  (avg fanout 8)
Calculating size of extent tree
Segmentation fault (core dumped)
```

**Comment by LaurentBonnaud** [comment]
Here is a backtrace:
```
(gdb) bt
#0  calc_root_size.isra.0 (key=key@entry=0x7fffffffe0f7, find_inline=find_inline@entry=0, tree_root=<optimized out>,
    tree_root=<optimized out>) at cmds/inspect-tree-stats.c:337
#1  0x00005555555bee2b in cmd_inspect_tree_stats (cmd=<optimized out>, argc=<optimized out>, argv=<optimized out>)
    at cmds/inspect-tree-stats.c:495
#2  0x000055555556bee8 in main (argc=3, argv=0x7fffffffe2a0) at /build/btrfs-progs-DQquNj/btrfs-progs-5.16.2/btrfs.c:405

```

**Comment by kdave** [comment]
There are two things to do here:
- update the warning that it can also crash, I think similar warning is in mkfs so this can be put to a common warning in case we allow that for more tools
- add more sanity checks that would at least exit gracefully in case invalid data are read

**Comment by kdave** [comment]
I've changed the message to:

```
warning("%s already mounted, tree-stats accesses the block devices directly, this may\n"
          "\tresult in inaccurate numbers, various errors or it may crash if the filesystem\n"
          "\tchanges unexpectedly, restart if needed or remount read-only", argv[optind]);
```

I don't see an immediate things to fix from the stack trace you posted. After some random tries on a filesystem that is under load I see transid errors, no crashes.
