### ISSUE TITLE
[cli-tests] 005-qgroup-show: memory leak

### ISSUE THREAD

**Issue by matthiaskrgr** [kdave/btrfs-progs#54]
compiled with ````clang 4.0````
CFLAGS: ````-O0 -g3 -fsanitize=address,undefined -fno-omit-frame-pointer````
based on maste branch / btrfs progs v4.12 / 0607132c3200bcead1426e6dc685432008de95de

````
=== Entering /home/matthias/vcs/github/btrfs-progs/tests/cli-tests/005-qgroup-show
$TEST_DEV not given, use /home/matthias/vcs/github/btrfs-progs/test/test.img as fallback
############### /home/matthias/vcs/github/btrfs-progs/mkfs.btrfs -f /home/matthias/vcs/github/btrfs-progs/tests/test.img
btrfs-progs v4.12-2-gb740108
See http://btrfs.wiki.kernel.org for more information.

Label:              (null)
UUID:               0a7fbc93-c713-45ab-bd97-02930cbe2dc8
Node size:          16384
Sector size:        4096
Filesystem size:    2.00GiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         DUP             102.38MiB
  System:           DUP               8.00MiB
SSD detected:       no
Incompat features:  extref, skinny-metadata
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1     2.00GiB  /home/matthias/vcs/github/btrfs-progs/tests/test.img

############### mount -t btrfs -o loop /home/matthias/vcs/github/btrfs-progs/tests/test.img /home/matthias/vcs/github/btrfs-progs/tests/mnt
############### /home/matthias/vcs/github/btrfs-progs/btrfs qgroup show /home/matthias/vcs/github/btrfs-progs/tests/mnt
ERROR: can't list qgroups: quotas not enabled

=================================================================
==14712==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 168 byte(s) in 1 object(s) allocated from:
    #0 0x4ca9c3 in calloc /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:74:3
    #1 0x64c576 in btrfs_qgroup_alloc_comparer_set /home/matthias/vcs/github/btrfs-progs/qgroup.c:440:8
    #2 0x767418 in cmd_qgroup_show /home/matthias/vcs/github/btrfs-progs/cmds-qgroup.c:309:17
    #3 0x4f854f in handle_command_group /home/matthias/vcs/github/btrfs-progs/btrfs.c:137:9
    #4 0x769814 in cmd_qgroup /home/matthias/vcs/github/btrfs-progs/cmds-qgroup.c:529:9
    #5 0x4f9423 in main /home/matthias/vcs/github/btrfs-progs/btrfs.c:302:8
    #6 0x7f308a755400 in __libc_start_main (/lib64/libc.so.6+0x20400)

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x4ca9c3 in calloc /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:74:3
    #1 0x64dbed in btrfs_qgroup_alloc_filter_set /home/matthias/vcs/github/btrfs-progs/qgroup.c:810:8
    #2 0x7673d7 in cmd_qgroup_show /home/matthias/vcs/github/btrfs-progs/cmds-qgroup.c:308:15
    #3 0x4f854f in handle_command_group /home/matthias/vcs/github/btrfs-progs/btrfs.c:137:9
    #4 0x769814 in cmd_qgroup /home/matthias/vcs/github/btrfs-progs/cmds-qgroup.c:529:9
    #5 0x4f9423 in main /home/matthias/vcs/github/btrfs-progs/btrfs.c:302:8
    #6 0x7f308a755400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: 240 byte(s) leaked in 2 allocation(s).
failed (ignored, ret=1): /home/matthias/vcs/github/btrfs-progs/btrfs qgroup show /home/matthias/vcs/github/btrfs-progs/tests/mnt
############### /home/matthias/vcs/github/btrfs-progs/btrfs qgroup show /home/matthias/vcs/github/btrfs-progs/tests/mnt
ERROR: can't list qgroups: quotas not enabled

=================================================================
==14718==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 168 byte(s) in 1 object(s) allocated from:
    #0 0x4ca9c3 in calloc /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:74:3
    #1 0x64c576 in btrfs_qgroup_alloc_comparer_set /home/matthias/vcs/github/btrfs-progs/qgroup.c:440:8
    #2 0x767418 in cmd_qgroup_show /home/matthias/vcs/github/btrfs-progs/cmds-qgroup.c:309:17
    #3 0x4f854f in handle_command_group /home/matthias/vcs/github/btrfs-progs/btrfs.c:137:9
    #4 0x769814 in cmd_qgroup /home/matthias/vcs/github/btrfs-progs/cmds-qgroup.c:529:9
    #5 0x4f9423 in main /home/matthias/vcs/github/btrfs-progs/btrfs.c:302:8
    #6 0x7f28c4813400 in __libc_start_main (/lib64/libc.so.6+0x20400)

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x4ca9c3 in calloc /home/matthias/LLVM/LLVM_4_0/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:74:3
    #1 0x64dbed in btrfs_qgroup_alloc_filter_set /home/matthias/vcs/github/btrfs-progs/qgroup.c:810:8
    #2 0x7673d7 in cmd_qgroup_show /home/matthias/vcs/github/btrfs-progs/cmds-qgroup.c:308:15
    #3 0x4f854f in handle_command_group /home/matthias/vcs/github/btrfs-progs/btrfs.c:137:9
    #4 0x769814 in cmd_qgroup /home/matthias/vcs/github/btrfs-progs/cmds-qgroup.c:529:9
    #5 0x4f9423 in main /home/matthias/vcs/github/btrfs-progs/btrfs.c:302:8
    #6 0x7f28c4813400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: 240 byte(s) leaked in 2 allocation(s).
failed (ignored, ret=1): /home/matthias/vcs/github/btrfs-progs/btrfs qgroup show /home/matthias/vcs/github/btrfs-progs/tests/mnt
############### /home/matthias/vcs/github/btrfs-progs/btrfs quota enable /home/matthias/vcs/github/btrfs-progs/tests/mnt
############### /home/matthias/vcs/github/btrfs-progs/btrfs qgroup show /home/matthias/vcs/github/btrfs-progs/tests/mnt
WARNING: rescan is running, qgroup data may be incorrect
qgroupid         rfer         excl 
--------         ----         ---- 
0/5          16.00KiB     16.00KiB 
############### /home/matthias/vcs/github/btrfs-progs/btrfs qgroup show /home/matthias/vcs/github/btrfs-progs/tests/mnt
WARNING: rescan is running, qgroup data may be incorrect
qgroupid         rfer         excl 
--------         ----         ---- 
0/5          16.00KiB     16.00KiB 
############### /home/matthias/vcs/github/btrfs-progs/btrfs quota disable /home/matthias/vcs/github/btrfs-progs/tests/mnt
############### umount /home/matthias/vcs/github/btrfs-progs/tests/test.img
````

**Comment by gujx2017** [comment]
patch:
https://patchwork.kernel.org/patch/9971571/

**Comment by kdave** [comment]
Thanks, the patch fixes just 2 of the leaks reported. I'll apply the patch and leave the issue open.

**Comment by gujx2017** [comment]
I am so sorry for patch(9971571) will bring a new problem of double free in normal scenes.
So I send a new patch.
https://patchwork.kernel.org/patch/9975383/

Please revert  patch(9971571) and use this new one.
