### ISSUE TITLE
Test check/013-extent-tree-rebuild fails with ASAN (leak)

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#806]
Build with `make D=asan` fails at the test case.

```
 ==40250==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4096 byte(s) in 1 object(s) allocated from:
    #0 0x7f6f3d0b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55b12762b639 in debug_corrupt_sector /home/runner/work/btrfs-progs/btrfs-progs/btrfs-corrupt-block.c:55
    #2 0x55b127634684 in main /home/runner/work/btrfs-progs/btrfs-progs/btrfs-corrupt-block.c:1626
    #3 0x7f6f3cc29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: 4096 byte(s) leaked in 1 allocation(s).
failed: /home/runner/work/btrfs-progs/btrfs-progs/btrfs-corrupt-block -l 58490880 -b 4096 /home/runner/work/btrfs-progs/btrfs-progs/tests/test.img
test failed for case 013-extent-tree-rebuild
```

**Comment by kdave** [comment]
Fixed in devel.
